name: Build Advanced Blueprint Tools V2 - Unity project 🎮

on: 
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
  # pull_request:
  #   branches: [ main ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    if: false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-
          restore-keys: |
            Library-
      
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}


  buildForSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: testAllModes
    strategy:
      fail-fast: false
      matrix:
        include:
          - unityVersion: 2020.3.14f1
            customImage: 'unityci/editor:ubuntu-2020.3.14f1-windows-mono-0.15'
            targetPlatform: StandaloneWindows64 # Build a Windows 64-bit standalone.
          - unityVersion: 2020.3.14f1
            targetPlatform: StandaloneLinux64 # Build a Linux 64-bit standalone.
    outputs:
      buildVersion: v${{ steps.build_project.outputs.buildVersion }}
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      
      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library--${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      
      # Build
      - name: Build project
        id: build_project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          versioning: Semantic
          customImage: ${{ matrix.customImage }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: ''
      
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}


  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: buildForSupportedPlatforms
    steps:
      - name: Download Build-StandaloneWindows64
        uses: actions/download-artifact@v2
        with:
          name: Build-StandaloneWindows64
          path: Build-StandaloneWindows64
        
      - name: Download Build-StandaloneLinux64
        uses: actions/download-artifact@v2
        with:
          name: Build-StandaloneLinux64
          path: Build-StandaloneLinux64
          
      - name: Archive Build-StandaloneWindows64
        uses: thedoctor0/zip-release@master
        with:
          filename: StandaloneWindows64.zip
          path: Build-StandaloneWindows64
          
      - name: Archive Build-StandaloneLinux64
        uses: thedoctor0/zip-release@master
        with:
          filename: StandaloneLinux64.zip
          path: Build-StandaloneLinux64
        
      # - name: Display structure of files
      #   run: ls -R
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.buildForSupportedPlatforms.outputs.buildVersion }}
          release_name: Release ${{ needs.buildForSupportedPlatforms.outputs.buildVersion }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset - StandaloneWindows64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./StandaloneWindows64.zip
          asset_name: StandaloneWindows64-${{ needs.buildForSupportedPlatforms.outputs.buildVersion }}.zip
          asset_content_type: application/zip
          
      - name: Upload Release Asset - StandaloneLinux64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./StandaloneLinux64.zip
          asset_name: StandaloneLinux64-${{ needs.buildForSupportedPlatforms.outputs.buildVersion }}.zip
          asset_content_type: application/zip
