name: Tagging

on:
  # Triggers the workflow on push or pull request events
  push:
    # branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        
jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2  
        with:  
          fetch-depth: 0  
            
      - name: Version  
        id: version  
        uses: juliansangillo/tag-version@v1  
        with:  
          production-branch: main  
          # test-branch: test
          dev-branch: development
            
