name: Bump tag

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        
jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump_tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main,release
        DEFAULT_BUMP: patch
        VERBOSE: false

    - name: echo
      run: |
        echo 'Old tag: ${{ steps.tag.outputs.new_tag }}'
        echo 'New tag: ${{ steps.bump_tag.outputs.new_tag }}'